### ISSUE TITLE
Changes to serverless.yml dont restart Webpack.

### ISSUE THREAD

**Issue by mikecann** [elastic-coders/serverless-webpack#10]
Hi, 

It would be nice if you changed serverless.yml or serverless.env.yml then webpack serve would restart. 

Not sure how hard that might be to do?

Mike

**Comment by thenikso** [comment]
Hmm it shouldn't be too hard, however a `ctrl-c` + `up`+ `enter` is doing a splendid job for me so far :P

I wouldn't add complexity to the plugin for hot reload a file that is hardly ever modified after the first setup. 

However I'll leave this here to see if other think this should be in. (also PR are welcome if you feel like trying it yourself!)

**Comment by mikecann** [comment]
Cool, no I understand what you mean regarding not wanting to add more complexity to the plugin tho I think while developing tho you are adding new functions all the time, its just another bit of friction.

Semi-related. If your function throws an error and crashes then it kills the whole thing which means you have to ctrl-c + up + enter again. It might be nice if on error it was able to restart.

If I get time ill have a look at implementing myself :wink:

**Comment by thenikso** [comment]
yes that would be great. I didn't go deep into errors enough. a recovery strategy when watching/serving might aid development of new lambdas. closing this for now
