### ISSUE TITLE
Webpack 2 support

### ISSUE THREAD

**Issue by pixeldrew** [elastic-coders/serverless-webpack#113]
Looks like I can't use webpack 2 configs. I had to revert to webpack 1. Has anyone got webpack 2 to work?

**Comment by rej156** [comment]
@pixeldrew git clone and private publish the module.
It seems the package.json on the github repository has a * for the peerDep version but it's not the case when you npm install the actual module.

**Comment by pixeldrew** [comment]
So this would be solved with a new release to npm.

**Comment by HyperBrain** [comment]
This has been fixed in #83 which allows using arbitrary Webpack versions, but is not yet deployed. Will be part of the next release. Until then you can reference the master branch as workaround.
We are using it together with Webpack 2 and since a few time also Webpack 3 and it is working very well.

**Comment by HyperBrain** [comment]
Released right now!
