### ISSUE TITLE
New release on NPM

### ISSUE THREAD

**Issue by hassankhan** [elastic-coders/serverless-webpack#115]
Hi there, could we get a new release on NPM please? Would be hugely appreciated 😄

**Comment by pixeldrew** [comment]
https://github.com/elastic-coders/serverless-webpack/issues/113 would also be solved with a new release

**Comment by blakedietz** [comment]
This would be great to see. There are quite a few prs out there. Is there anything that the contributors can do to help out with getting them merged in sooner?

**Comment by ahmednuaman** [comment]
I'm happy to help. I'd like to see #113 resolved so happy to roll my sleeves up. 💪

**Comment by mmahalwy** [comment]
Bump pleasse!

**Comment by mschinis** [comment]
@thenikso ^

**Comment by HyperBrain** [comment]
Just released
