### ISSUE TITLE
(ReactJS + serverless) static served page vs virtual DOM bug

### ISSUE THREAD

**Issue by leongaban** [elastic-coders/serverless-webpack#125]
http://stackoverflow.com/questions/44052476/reactjs-serverless-static-served-page-vs-virtual-dom-bug?noredirect=1#comment75130440_44052476

**Expected:** We see our React app, rendered staticly with all the Markup and logic inside of the view, to be served up so Users & Web crawlers can read text and follow links.

**Results:** We see nothing in the page.

=====

We are rending serverside ReactJS components with **serverless-webpack**

Everything is working great, the component data/markup is rendered out. However the problem happens when we run serverless webpack serve

We hit the localhost link and for a split sec we see the app, then it's gone to a white page.

On deeper inspection if we do a View Source, we see ALL the markup, including CSS and JS, everything. However in the Chrome Inspector we only see the app <div> and nothing else. It's like once our app script line runs, we replace the static content with the Virtual DOM.

To those are who rendering static pages with React and serverless, how have you overcome this problem?

**Comment by HyperBrain** [comment]
@leongaban With version 3 (available as `3.0.0-rc.2` now) we switched completely to use `serverless-offline` and `serverless invoke local` to concentrate on the packaging and not emulation. Does that solve your problem?

**Comment by HyperBrain** [comment]
As there has been no recent feedback, I'll close the issue. Feel free to reopen it or create a new one for the latest plugin version if it persists.
