### ISSUE TITLE
Auto install npm dependancies when they are added to code with npm-install-webpack-plugin

### ISSUE THREAD

**Issue by DavidWells** [elastic-coders/serverless-webpack#13]
Have you seen: https://github.com/ericclemmons/npm-install-webpack-plugin ?

It automatically with add deps to package.json and `npm i` them for you.

Just an idea. Might be out of scope or something the custom webpack config would do.

**Comment by thenikso** [comment]
Cool, it would be nice to see if it "just works" by adding it to the webpack configuration. I don't have time myself at the moment tho.

Ideally having started the `serverless webpack watch` or `serve` with that plugin might just do the trick. Leaving this open if someone wants to report in

**Comment by mikestaub** [comment]
I tested this out today and it does in fact "just work". Here is my webpack config:

https://gist.github.com/mikestaub/cfcce4bcff0ac14ae3609d2f91305c4e

One caveat is that I needed to add this line to the entry file, otherwise babel-polyfill will throw an error:

```
if (!global._babelPolyfill) {
  require('babel-polyfill');
}
```

**Comment by thenikso** [comment]
Thanks @mikestaub ! This issue should provide enough support for now. We might add some doc in the readme if ppl hit +1 here
