### ISSUE TITLE
Add serverless create template

### ISSUE THREAD

**Issue by franciscocpg** [elastic-coders/serverless-webpack#137]
In the future we could add a template [here](https://github.com/serverless/serverless/tree/master/lib/plugins/create/templates) so that new serverless projects can be created with webpack already configured.

**Comment by HyperBrain** [comment]
Wow. Nice idea 🙌 . That would make the project creation really easy.
Can you create an issue in the serverless core repo and link it here, so that we can track it properly?

Then we can work and comment on a PR there - that one of us (maybe you 😄 ) initially created to get a nice template in there.

**Comment by franciscocpg** [comment]
Yes @HyperBrain 
I just want to focus on https://github.com/elastic-coders/serverless-webpack/pull/130 before because IMO it will have some influence here.

**Comment by HyperBrain** [comment]
@franciscocpg 2.1.0 is out now! Maybe you can proceed here as soon as you have some time.

**Comment by franciscocpg** [comment]
Sure @HyperBrain 
I'm thinking about using [examples/babel-multiple-statically-entries](https://github.com/elastic-coders/serverless-webpack/tree/master/examples/babel-multiple-statically-entries) as our "model" (with some changes, of course) to create a new template called `aws-nodejs-ecma-script` (need suggestions for name) based on [templates/aws-nodejs](https://github.com/serverless/serverless/blob/master/lib/plugins/create/templates/aws-nodejs).
That's because IMO the main reason to use `serverless-webpack` is enabling ecma-script code style.

**Comment by franciscocpg** [comment]
Oh and maybe we need to add a `aws-nodejs-typescript` using [examples/typescript](https://github.com/elastic-coders/serverless-webpack/tree/master/examples/typescript) as our model?

**Comment by HyperBrain** [comment]
... and #167 will remove the extension from the entry key names, so that `[name].js` has to be used as `output`. We should take that into account. There was a problem with typescript support ( #165 ) that will be solved there by determining the correct handler filenames. I try to release these fixes as 2.2.0 as soon as the implementations are stable.

**Comment by HyperBrain** [comment]
see also the discussion in #158

**Comment by franciscocpg** [comment]
So I think it's better wait for 2.2.0.

**Comment by HyperBrain** [comment]
2.2.0 is out. Had to be that fast, because of the TypeScript issue with the entries export 😃 .

You can proceed here now.

**Comment by HyperBrain** [comment]
I agree that there should be more than one template - the multi-static and the typescript.

We can add one that is missing later: the multi-dynamic, as soon as it is proven that the entries detection works properly now. Imo the dynamic template(s) should be the preferred ones in the future.

**Comment by franciscocpg** [comment]
@HyperBrain 
So how I about creating these two first templates (`name` / `example model`)
`aws-nodejs-ecma-script` - [examples/multiple-statically-entries](https://github.com/elastic-coders/serverless-webpack/tree/master/examples/multiple-statically-entries)
`aws-nodejs-typescript` - [examples/typescript](https://github.com/elastic-coders/serverless-webpack/tree/master/examples/typescript).
IMO these two are the ones that add more value to the serverless community that wants to use ES or typescript with serverless framework.

**Comment by HyperBrain** [comment]
I would use the dynamic sample. Imo this is the preferred way now to configure the plugin/webpack in an easy and safe way. Much easier than finding out and adding new entries or removing stale ones when you add or remove functions.
But yes, ES and TS should be the choice for them.

**Comment by franciscocpg** [comment]
Ops, I've put the wrong example.
I've edited the https://github.com/elastic-coders/serverless-webpack/issues/137#issuecomment-319768537
So those two ones?

**Comment by HyperBrain** [comment]
I would prefer babel-dynamically-entries. Both samples TS and ES should use lib.entries for the entry definition.

**Comment by HyperBrain** [comment]
Oh. did not refresh 😄 ... yes, right

**Comment by franciscocpg** [comment]
:+1: 
WIP

**Comment by HyperBrain** [comment]
BTW: The lib extensions are really a great thing - did you see that I extended it with `lib.serverless` and `lib.options` in the 2.2.0 release? Now you can have stage dependent configurations with only one webpack.conf.js.

**Comment by franciscocpg** [comment]
@HyperBrain 
Just opened #179 to upgrade examples.
Next steps are:
- [ ] Create an issue to propose new templates (Eg: https://github.com/serverless/serverless/issues/3969)
- [ ] Create the PR (Eg: https://github.com/serverless/serverless/pull/3970)

**Comment by HyperBrain** [comment]
I already merged #179 . It would be great if you open proper issues at SLS and link them here.

**Comment by franciscocpg** [comment]
:+1: , Leave it to me

**Comment by franciscocpg** [comment]
Adding `aws-nodejs-ecma-script` template: https://github.com/serverless/serverless/pull/4056
Adding `aws-nodejs-typescript` template: https://github.com/serverless/serverless/pull/4058
