### ISSUE TITLE
Add note about new required Webpack peer dependency to README

### ISSUE THREAD

**Issue by HyperBrain** [elastic-coders/serverless-webpack#138]
# This is a Feature Proposal

## Description

PR #83 which already has been merged to master is a breaking change. It offers users to use the webpack version of their choice, which is really helpful, but demands a change of the project dependencies, i.e. projects using the upcoming version must install a webpack version through their dependencies.

From a versioning perspective the upcoming version will be 2.0.0 then, to not break existing installations.

**We should add a note to the README, that informs people about this change and its availability in version 2.0.0.**

**Comment by HyperBrain** [comment]
Imo the note should be placed somewhere at the top of the README, so that it is seen on a first glance when opening the npmjs page or GitHub.

**Comment by hassankhan** [comment]
#140 ready for review 👍
