### ISSUE TITLE
How do you use other NPM modules?

### ISSUE THREAD

**Issue by mikecann** [elastic-coders/serverless-webpack#14]
Suppose I want to use a third party lib such as `axios` how do I go about doing that?

If I `import * as axios from "axios";` then run `sls webpack serve` I get the following error:

```
ReferenceError: XMLHttpRequest is not defined
    at dispatchXhrRequest (C:\Projects\Experiments\my-third-service\.webpack\handler.js:1045:24)
    at xhrAdapter (C:\Projects\Experiments\my-third-service\.webpack\handler.js:1037:11)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

If I include `axios` in the externals of webpack.config.js:

```
externals: [
    'axios'
  ],
```

The code runs but after `sls deploy` I get the following error when I try to run the function:

```
{"errorMessage":"Cannot find module 'axios'","errorType":"Error","stackTrace":["Module.require (module.js:353:17)","require (internal/module.js:12:17)","Object.<anonymous> (/var/task/handler.js:132:19)","__webpack_require__ (/var/task/handler.js:20:30)","Object.<anonymous> (/var/task/handler.js:51:14)","__webpack_require__ (/var/task/handler.js:20:30)","/var/task/handler.js:40:18","Object.<anonymous> (/var/task/handler.js:43:10)"]}
```

Any ideas? Perhaps an example that uses a third party lib would be good?

**Comment by cyyuen** [comment]
I think we should pack the external packages into dist when deploy. We could use npm to resolve all the external dependencies which are stated in webpack config.

**Comment by thenikso** [comment]
see #16 in the works by @cyyuen. I think it could be a great way to solve the issue

**Comment by mikestaub** [comment]
Hi guys, I have some issues with the current approach, please see my PR for details: https://github.com/elastic-coders/serverless-webpack/pull/18

**Comment by thenikso** [comment]
This should now be at least doable in beta.2.2 with #16 in it. Further improvements as discussed in #18 might occur in the future. Closing this
