### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by hassankhan** [elastic-coders/serverless-webpack#141]
# This is a Feature Proposal

## Description

There's a few minor nitpicks in the `README.md` file. It would also be nice to have badges for NPM etc. for getting project status quickly.

**Comment by hassankhan** [comment]
Some examples:

https://github.com/elastic-coders/serverless-webpack/blame/master/README.md#L6
https://github.com/elastic-coders/serverless-webpack/blame/master/README.md#L119

**Comment by HyperBrain** [comment]
I have working badges for NPM, Travis and Coveralls in the alias plugin (they create svg badges for smooth rendering): https://github.com/HyperBrain/serverless-aws-alias/blob/master/README.md
