### ISSUE TITLE
Add a license badge to the README

### ISSUE THREAD

**Issue by HyperBrain** [elastic-coders/serverless-webpack#146]
# This is a Feature Proposal

## Description

It would be good to have the license (MIT) displayed at the top of the README, so that people and companies who must comply to specific regulations can see it on the first glance.

A sample can be found here: https://github.com/arabold/serverless-sentry-plugin

## Additional Data

_None_

**Comment by hassankhan** [comment]
Dang, I forgot to add it. Expect a PR shortly 😉
