### ISSUE TITLE
DOCs: Example 'multiple-entries' is failing

### ISSUE THREAD

**Issue by lpgeiger** [elastic-coders/serverless-webpack#150]
# This is a Bug Report 

## Description

For bug reports:
* What went wrong?
Using the example called  'multiple-entries', the 'first.js' script doesn't seem to be loading, or returning correctly.
* What did you expect should have happened?
expect to see in browser with GET: `{ message: 'First module' }`
* What was the config you used?
The default in the example. No changes
* What stacktrace or error message from your provider did you see?
No errors logged :(

## Additional Data
I'm using all the dependencies in the package.js, with no changes.

* ***Serverless-Webpack Version you're using***:
* ***Webpack version you're using***:
* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace (if available)***:

**Comment by HyperBrain** [comment]
@lpgeiger How did you run the example? Did you use `webpack serve`, `serverless-offline` or did you deploy the sample? It would be quite helpful if you let us know how to reproduce this exactly 😃 .

**Comment by HyperBrain** [comment]
@lpgeiger Any update on this?

**Comment by lpgeiger** [comment]
@HyperBrain yes I ran it with `webpack serve`. It's strange since no logs are showing. I'm guessing you have made it work in your environment.

**Comment by HyperBrain** [comment]
We do not use the `serve` command at all at work. We just use `serverless-offline`. The `serve` command will be abandoned with one of the next releases, because it does the simulation of API Gateway much better.
Could you give it a try? The webpack plugin's README has some information about how to use it.

**Comment by HyperBrain** [comment]
BTW: The samples changed a bit with version 2.1.0 and 2.2.0 and some new ones were added. Mostly because of the new dynamic entry support.

**Comment by franciscocpg** [comment]
@lpgeiger 
Is the problem still occurring?

**Comment by lpgeiger** [comment]
@HyperBrain Ok I'm guessing the examples were out of date, I will try now. I see an 'offline' example int he directory. Thanks, we can close now.
