### ISSUE TITLE
Remove the serve command

### ISSUE THREAD

**Issue by HyperBrain** [elastic-coders/serverless-webpack#152]
# This is a Feature Task

## Description

In #135 we decided that the `serve` command will be removed because it does
not add additional value to the Serverless framework as the `serverless-offline`
integrates with the plugin and does the job even better.

This task should contain all (technical) discussions about the actual removal, so
that it can be removed without affecting the other commands/features that will stay 
in the plugin.

The target milestone for the removal is version 3.0.0 as it is (by definition) a breaking change
that needs actions to be taken by users that currently use it.

All PRs for the feature have to be targeted to the (new) `v3.0.0-remove-serve` branch to keep master clean
for any 2.x.x bugfix or feature versions. We will use this branch to stabilize the feature. The branch will be
rebased to master each time something is added there.

Similar or dependent issue(s):
* #135

**Comment by HyperBrain** [comment]
@hassankhan Are you interested (and have time) to take care of this?

Additionally to removing the command, we also have to check for then obsolete dependencies that can be removed from the project.

**Comment by HyperBrain** [comment]
I can take care of the "local invoke" (#151) which would also be a good addition to 3.0.0.

**Comment by hassankhan** [comment]
I'll try and commit some time to it, as you said it needs to be carefully done and not break anything else. I'd add that it should probably be tested with `serverless-offline` thrown into the mix just in-case there's anything weird going on there.

**Comment by HyperBrain** [comment]
I'll add the new `issue/serve` label to all issues regarding the serve command. These issues should not be worked on and they should be closed as soon as `serve` has been removed.

**Comment by bebbi** [comment]
I've tried to run

`serverless offline start`

instead of

`serverless webpack serve`

In the `offline` way, the lambdas get called, execute correctly - but they don't return a json body as they do with the `serve` way. I don't see any related issue in `serverless-offline`, maybe something related to `serverless-webpack`?

I'm happy to troubleshooting but don't know where to start.

**Comment by HyperBrain** [comment]
@bebbi Maybe someone who commented in #135 can help out here. Can you post this question there (and address the ones who answered directly)?

**Comment by franciscocpg** [comment]
@bebbi 
Is your response in this [format](https://github.com/franciscocpg/serverless-offline/blob/master/manual_test/handler.js#L4)?

**Comment by bebbi** [comment]
@franciscocpg , answered in #135 per @HyperBrain request.

**Comment by bebbi** [comment]
This might be a good place for tracking two pending sls-offline PRs on blocking issues for some use-cases for discarding the serve command -

https://github.com/dherault/serverless-offline/pull/283
https://github.com/dherault/serverless-offline/pull/285
