### ISSUE TITLE
serverless-offline exec is broken

### ISSUE THREAD

**Issue by jgilbert01** [elastic-coders/serverless-webpack#154]
# This is a Bug Report

## Description

Serverless-offline has a nifty feature called scoped execution that can be used for automated integration testing.
* https://www.npmjs.com/package/serverless-offline#scoped-execution

This exec feature is currently not working with serverless-webpack because the tests get executed before webpack watch has a chance to compile the source.

## Proposed Solution

The proposed solution is to execute compile after validate and before watch. This will force a compile when serverless-offline is started but before the tests are executed and still support watch for non automated scenarios that do not have the race condition.

## Additional Data

* ***Serverless-Webpack Version 2.0.0***:
* ***Webpack version 3.0.0***:
* ***Serverless Framework Version 1.17.0***:
* ***Serverless-Offline Version 3.15.0***:

**Comment by jgilbert-hobsons** [comment]
thx for accepting this merge request. is there any plan to publish a new version to npm?

**Comment by HyperBrain** [comment]
Most likely today ;-)

**Comment by jgilbert-hobsons** [comment]
Excellent!!
