### ISSUE TITLE
Functionability for individual packaging when deploying single function

### ISSUE THREAD

**Issue by nicolasdonoso** [elastic-coders/serverless-webpack#183]
v3.0.0 is working correctly when I deploy a function that has been already inside a complete deploy of the project. But every time I try to add a new function a get an error like the following one:

node_modules/.bin/sls deploy function -f notifier-progress

  Serverless Error ---------------------------------------

  The function "notifier-progress" you want to update is not yet deployed. Please run "serverless deploy" to deploy your service. After that you can redeploy your services functions with the "serverless deploy function" command.
The main fact to use single functions deployments is to avoid deploying everything, but this is only letting me add changes to functions that are already created and not to add new ones to my project with out have to deploy all.
Is this considered on the estable v3.0.0??

**Comment by fcheong3b** [comment]
I'm having the same issue in my project I saw the new release of the version 3 and after couple of tests I got the same problem, If I want to add a new function I can do it as an individual function instead  I have to deploy all the serverless project again a then I'm able to do it. I thought the individual function deploy functionality was including deploying new function without deploying all the project. Is it going to be soon?

**Comment by HyperBrain** [comment]
@nicolasdonoso @fcheong3b This is a restriction of Serverless and not the plugin. The reason, why you cannot "add" a new function with `deploy function` is, that Serverless uses the AWS API to upload the function code. But for that to work the function has to be deployed already.

I agree that this would be a nice feature, but it has to be added as feature request in Serverless. Feel free to open an issue there - technically it should be possible to add something like this to the framework, although it is not trivial.

**Comment by nicolasdonoso** [comment]
@HyperBrain thanks for the feedback, I will submit the issue on Serverless project.

**Comment by HyperBrain** [comment]
Closing this now as it is a limitation of the Serverless framework. Let's the guys do it 😄
