### ISSUE TITLE
Examples missing a .babelrc or a babel configuration in package.json

### ISSUE THREAD

**Issue by nikgraf** [elastic-coders/serverless-webpack#194]
# This is a Question

Did I miss something?

**Comment by HyperBrain** [comment]
@franciscocpg You experimented with the new updated samples. Maybe you can help out here?

**Comment by HyperBrain** [comment]
Just my 2 cents: You do not need any explicit babel configuration as you can do that completely in your `webpack.config.js` with the loader/preset configuration. However, webpack should use any babelrc or package.json configuration if present (according to its documentation).

**Comment by HyperBrain** [comment]
Was my throw-in helpful, or are there any further things unclear for this? Would it be helpful to include a special sample that overrides the webpack config with a `.babelrc`?

**Comment by franciscocpg** [comment]
Sorry for the delay here.
What example specifically are you talking about @nikgraf?
`babel` example has a `.babelrc` file. 
`babel-dynamically-entries` and `babel-multiple-statically-entries` are using [babel-loader](https://github.com/babel/babel-loader) plugin so you don't need a `.babelrc` because options can be inside `webpack.config.js`. Reference: https://github.com/babel/babel-loader#options.

**Comment by HyperBrain** [comment]
@nikgraf @franciscocpg I just verified the compatibility of `.babelrc` and `webpack.conf.js` in one of our projects. In general, it does not matter how you build your project configurations, all natural combinations work. These are possibilities you have:

### Webpack config only
Configure the `babel-loader` completely in `webpack.conf.js` (no .babelrc).

### Webpack config + .babelrc
Enable the `babel-loader` in `webpack.conf.js`, let the options object be empty.
Configure the options in a `.babelrc`. Webpack will use the babel-loader with the options given in .babelrc.
Use this, if you use `babel-register` in parallel to have your unit test framework (e.g. Mocha) compile the code on-the-fly (`--compilers` switch). Babel-register uses the .babelrc then to configure it's require hook as well as webpack to configure its compile.

@nikgraf Is there anything else to be answered here, or can we close the issue?

**Comment by nikgraf** [comment]
ahhh right, sounds good to me. sorry for the confusion

**Comment by aakhan89** [comment]
> 
> 
> ahhh right, sounds good to me. sorry for the confusion

What was the issue ? I have same issue, kindly let me know the solution, Thank you
