### ISSUE TITLE
Error on first serverless deploy

### ISSUE THREAD

**Issue by kennu** [elastic-coders/serverless-webpack#20]
When deploying a new Serverless project for the first time (stack doesn't exist in CloudFormation yet) with `sls deploy`, I see this error:

    $ sls deploy
    Serverless: Creating Stack...
    Serverless: Checking stack creation progress...
    ......
    Serverless: Stack successfully created.
    Serverless: Bundling with Webpack...
    Time: 4537ms
           Asset    Size  Chunks             Chunk Names
    ./handler.js  268 kB       0  [emitted]  main
    Serverless: Zipping service...
     
      Error --------------------------------------------------
     
         EEXIST: file already exists, link '/Users/kennu/Projects/xxx/xxx/services/.webpack/.serverless'
         -> '/Users/kennu/Projects/xxx/xxx/services/.serverless'
     
         For debugging logs, run again after setting SLS_DEBUG env var.
     
      Get Support --------------------------------------------
         Docs:          v1.docs.serverless.com
         Bugs:          github.com/serverless/serverless/issues
     
         Please report this error. We think it might be a bug.
    

When I run `sls deploy` again, it works fine.

**Comment by thenikso** [comment]
Interesting, I'll ding on this

**Comment by voidfiles** [comment]
I'm running into this, and no matter how many times I run deploy it breaks.

**Comment by demirhanaydin** [comment]
@voidfiles I've faced with the same issue. This small change fixes the problem https://github.com/demirhanaydin/serverless-webpack/commit/464d34e93b403ee02c58c7b56c9ddce0729c7403

**Comment by bxjx** [comment]
Got this also. @demirhanaydin fix worked for me.

**Comment by khoaisohd** [comment]
Could you publish a new version for this fix?

**Comment by mschinis** [comment]
Ran into this earlier today, is it possible to get this merged in?

**Comment by tuler** [comment]
Is there any workaround (without changing the source)? Maybe through a command line option.

**Comment by thenikso** [comment]
Version 1.0.0-rc.2 is on npm with this fix!
