### ISSUE TITLE
Issue with serverless-webpack and serverless-dynamodb-local, crosspost

### ISSUE THREAD

**Issue by bebbi** [elastic-coders/serverless-webpack#203]
Since serverless-webpack and serverless-dynamodb-local are an often-used combo, I'm simply cross-posting the issue here in case someone is searching here or this issue might be related to using serverless-webpack at all.
https://github.com/99xt/serverless-dynamodb-local/issues/127

**Comment by HyperBrain** [comment]
Serverless-webpack only hooks into offline's lifecycle. Something with the hooks in dynamodb-local might have changed in an incompatible way.

**Comment by bebbi** [comment]
Good to know. Lets continue over at serverless-dynamodb-local.
