### ISSUE TITLE
"No matching handler found" when handlers aren't in the root folder

### ISSUE THREAD

**Issue by jerep6** [elastic-coders/serverless-webpack#207]
# This is a (Bug Report)
Since the version 2.2 and [this PR](https://github.com/elastic-coders/serverless-webpack/pull/167/) my config is broken.

## Description
When the lambda handlers aren't in the root folder (this.serverless.config.servicePath) serverless-webpack doesn't find them.
> $ serverless deploy
>   Serverless Error ---------------------------------------
>   No matching handler found for 'TestHandler'. Check your service definition.

Reading the code, I understand that the plugin is looking for the files in the root folder, but in my project, neither the original typecript files nor the transpired files are there.
````
const files = glob.sync(`${fileName}.*`, {
        cwd: this.serverless.config.servicePath,
        nodir: true
      });
````

The hierarchy:
````
-app
  - handlers/ (all the lambda handlers)
-dist (webpack output path)
-serverless.yml
-webpack.config.js
-package.json
````
## Additional Data

I initialized a test repo to show the behavior: https://github.com/jerep6/serverless-webpack-issue

* ***Serverless-Webpack Version you're using***: 2.2.2
* ***Webpack version you're using***: 3.3.5
* ***Serverless Framework Version you're using***: 1.19.0
* ***Operating System***: MacOS

**Comment by HyperBrain** [comment]
This is because your handler definition in your `serverless.yml` seems to not match your handler locations.
In Serverless, function handlers have to point to their respective locations if located in subdirectories.

`serverless-webpack` since version 2.2 enforces that the definitions are correct.

Can you please check if your handler definitions in `serverless.yml` are correct? I.e. if your handler file is somewhere in `<service_dir>/src/handlers/myhandler.js` the handler definition in the yaml file must be `src/handlers/myhandler.myfunc`.

**Comment by HyperBrain** [comment]
@jerep6 If you don't mind you also can try the (in V2.2) new entry auto-resolution with `slsw.lib`. That makes the whole process more stable and also enables you to use V3 later with individual packaging. (V3 is already available as `^3.0.0-rc.2` and I consider it stable right now. 😃

**Comment by jerep6** [comment]
Indeed, the behavior has changed. Now you have to enter the full path to the handler.

Thanks.

How does serverless-offline execute transpiled files by serverless-webpack? Before I specified the argument "--location dist" when running serverless-offline.

**Comment by HyperBrain** [comment]
You can omit the location parameter as far as I got from multiple responses from multiple people with V2 (before you had to set it to `.webpack` if you used a default output configuration like:
```js
// webpack.conf.js
...
output: {
  ...
  path: path.join(__dirname, ".webpack"),
  ...
}
...
```
in your webpack config (dist if you used that). In general people do not complain or have issues with serverless-offline. That's the reason why that's the proposed way to execute locally for V3 (V3 also supports integration with `serverless invoke local` to execute a single function with a prepared event.json).

V3 will automatically set location properly to support all possible service configurations.

**Comment by HyperBrain** [comment]
@jerep6 Did you try with V3 or solve the issue in a different way?

**Comment by jerep6** [comment]
Yes it works with v3, auto-resolution with slsw.lib and the full path to the handler.

Thanks

**Comment by HyperBrain** [comment]
Closing the issue as you found a solution 😃
