### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by EdByrnee** [elastic-coders/serverless-webpack#212]
# This is a Bug Report

## Description

When invoking locally on a fresh project I get
`
Error: Cannot find module '/Users/edwardbyrne/Desktop/my-service/handler'`

## Webpack.config.js
```
const path = require('path');
// eslint-disable-next-line import/no-unresolved
const slsw = require('serverless-webpack');

module.exports = {
  entry: slsw.lib.entries,
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  target: 'node',
  module: {
    loaders: [
      { test: /\.ts(x?)$/, loader: 'ts-loader' },
    ],
  },
};


```

**Comment by HyperBrain** [comment]
Did you use version 3 or version 2.2.2? `2.2.2` does not support invoke local yet, you have to use `3.0.0-rc.2` for that.

**Comment by EdByrnee** [comment]
Ah silly me the serverless cli installs 2.2.2 as default. Thanks!
