### ISSUE TITLE
Webpack's Node mock objects should be disabled

### ISSUE THREAD

**Issue by kennu** [elastic-coders/serverless-webpack#22]
By default, Webpack mocks various Node.js objects, causing e.g. Buffer incompatibilities when calling native node_modules.

The default webpack.config.js should include these settings, in documentation or in some other default:

    node: {
      console: false,
      global: false,
      process: false,
      Buffer: false,
      __filename: false,
      __dirname: false,
      setImmediate: false,
    }

**Comment by andymac4182** [comment]
@kennu Did you have to set this as well as setting `target: node` ?

**Comment by kennu** [comment]
I didn't set target:node anywhere, I just added those things and it started to work.

**Comment by andymac4182** [comment]
https://webpack.github.io/docs/configuration.html#target I set this to node and I was able to remove that whole section.

**Comment by kennu** [comment]
Okay cool, I guess that should be mentioned in the serverless-webpack documentation README.

**Comment by thenikso** [comment]
added an example `webpack.config.js` in the readme with `target: 'node'`. thanks for bringing this out!
