### ISSUE TITLE
Update cwd when invoking function locally

### ISSUE THREAD

**Issue by andymac4182** [elastic-coders/serverless-webpack#25]
From what I can see the current working dir isn't updated before calling a function which stops some relative path locations locally

I believe `process.chdir(path.dirname(handlerFilePath))` should be inserted before https://github.com/elastic-coders/serverless-webpack/blob/master/lib/run.js#L16 

This will help with https://github.com/serverless/serverless/issues/2009

**Comment by thenikso** [comment]
I'd like too see an example that beaks this (so that we could write a test for it). Also I'm not entirely sure on how to handle this with multiple entryponts/outputs.
