### ISSUE TITLE
Work with serverless-offline plugin

### ISSUE THREAD

**Issue by andymac4182** [elastic-coders/serverless-webpack#29]
The `serverless-offline` plugin has a large support for handling most of the emulation of API Gateway. It would be great if I could use this plugin with that one to get a great offline experience and the great processing experience I am having with this plugin. 

Not sure if this is something you can work with the author of that plugin on.

**Comment by thenikso** [comment]
It would be great so that this plugin could only be doing the compilation phase. `serverless-offline` doesn't seam to be released for v1 at this time tho. I'll check it out in the future

**Comment by andymac4182** [comment]
They have a branch where they are working at the moment. I would guess they will release close to when 1.0 is actually released.

**Comment by thenikso** [comment]
which makes sense because keeping up with 1.0 betas/rcs timing is quite challenging xD

**Comment by thenikso** [comment]
Follow PR #55 for updates on this
