### ISSUE TITLE
promises - getting errors ?

### ISSUE THREAD

**Issue by andyfenelon** [elastic-coders/serverless-webpack#31]
seem to be getting an error whenever i use a promise ? i cloned the babel example to test it and still getting the same error 

> 	$export($export.S + $export.F * !__webpack_require__(20), 'Object', { defineProperty: __webpack_require__(16).f });
> 	^
> 
> TypeError: $export is not a function

```
function p1(){
  return new Promise((resolve, reject) => {
    setTimeout(_ => {
      resolve('yolo')
    },200)
  })
}
```

**Comment by thenikso** [comment]
Hi, I solved this in the esample. see here https://github.com/elastic-coders/serverless-webpack/commit/b63f3c8bf83ba50b2ecef357a9daf46be9154c87

**Comment by andyfenelon** [comment]
thanks.

**Comment by andyfenelon** [comment]
that change is causing an error when any lib module get imported.

> Error: only one instance of babel-polyfill is allowed


i got it to work by moving in to the top of the handler and .removing it from webpack.config

handler.js
`import 'babel-polyfill';`
