### ISSUE TITLE
"Can't set headers after they are sent." Error using "request" package

### ISSUE THREAD

**Issue by outsidenote** [elastic-coders/serverless-webpack#33]
Hi,

Love your package.
It makes our serverless projects much cleaner and easier to test/deploy.

We've encountered a weird bug where in some cases (couldn't pin which one) using the request package will invoke the error mentioned in the title.

We're using very basic code which breaks, so we assume there is some kind of problem with the bundling...

Code example:

``` javascript
new Promise((resolve, reject) => {
    request.get(endpoint, (err, response, body) => {
      if (err)
        return reject(err)
      const { statusCode } = response
      if (statusCode !== 200)
        return reject(`Response with status code ${statusCode}`)
      return resolve(body)
    })
  })
```

Help would be much appreciated, thanks!

**Comment by thenikso** [comment]
this looks more like a problem in the way you are using the response object ie http://stackoverflow.com/questions/7042340/node-js-error-cant-set-headers-after-they-are-sent
