### ISSUE TITLE
Allow content-type aliases for body parser

### ISSUE THREAD

**Issue by blackxored** [elastic-coders/serverless-webpack#34]
Seems like body parser correctly uses `bodyParser.json`, however we're not allowed to pass an alias to specify a specific content type should be parsed as JSON. As a result most webhook APIs that specify this hypermedia-like content-type (e.g `application/vendorname+vendorversionmaybe-vendortypemaybe+json`) result in an empty body for `sls webpack serve`'s express app. This library should support this use case by either:
- Interpret anything with `json` in the content-type as JSON.
- Allowing client to specify response content-type aliases; correct me if I'm wrong but since API Gateway doesn't seem to have this problem for me, the culprit (and fix) seems to belong here.

EDIT: link to the specific body parser option I'm referring to: https://github.com/expressjs/body-parser#type
EDIT 2: The first scenario should be covered in the simplest way by this:

``` javascript
 app.use(bodyParser.json({ limit: '5mb', type: function(req) {
   return /json/.test(req.headers['content-type']);
 }}));
```

on `lib/serve.js#_newExpressApp`.

**Comment by thenikso** [comment]
nice, I'll add this and publish in rc.3

**Comment by thenikso** [comment]
Actually I added the snipped you suggested, for scenario 2 a PR / idea on how to do it would be great. Also let's see if other come to this issue
