### ISSUE TITLE
Deploying independent functions doesn't work.

### ISSUE THREAD

**Issue by j** [elastic-coders/serverless-webpack#35]
I just attempted deploying a single function instead of all of them:

``` bash
$ serverless deploy function -f myFunction
```

It didn't show any build information and broke the endpoint.

I'd hate to have to deploy all my functions each build.  Is this a possibility?

**Comment by andymac4182** [comment]
It doesn't take any longer to deploy them all than it does one. The hooks aren't there for minifying as part of deploying a single function. 

What is better when deploying a single function than keeping them all up to date?

**Comment by thenikso** [comment]
It should at least not break everything. Anyone investigated into this?

**Comment by thenikso** [comment]
#48 should fix this
