### ISSUE TITLE
Add interactive debugging support

### ISSUE THREAD

**Issue by utkuturunc** [elastic-coders/serverless-webpack#42]
node-debug/node-inspector or webstorm/vscode can be used in order to debug functions locally.

**Comment by thenikso** [comment]
I think this would require to start the whole thing with a `--debug` option to node.. I wonder how we could do this. I guess that starting serverless in debug mode should do.

**Comment by utkuturunc** [comment]
#47 should solve this issue. serverless-offline has debugger support.

**Comment by gertjvr** [comment]
refering to [https://github.com/node-inspector/node-inspector#advanced-use

Steps to debug locally.
- run `serverless webpack serve`
- signal node process to enter debug mode (find the process id)
  - linux: `kill -s USR1 {process id}`
  - windows: `node -e "process._debugProcess({process id})"
- use your debugging ide / tool of choice and connect remote debugging

**Comment by utkuturunc** [comment]
@gertjvr thanks. that works.

how can i use sourcemaps with this method and use the debugger on prebabel transpiled surces?

**Comment by gertjvr** [comment]
been pulling my hear out, only webstorm seems to be able to debug sourcemaps

**Comment by utkuturunc** [comment]
I tried with `devtools: "source-map"` in webpack and also set `"sourcemaps": true` in launch.json (vscode)

Webstorm mostly works including editing, but in console I have to use  _logger2.default.info() instead of logger.info()

In VSCode, I have to put my breakpoints in .webpack folder but it will stop at mapped files. If webstorm can do it, this must be either missing feature on vscode's part or misconfiguration on my part. I cannot get it to listen to the breakpoints in my source code.

In Chrome Debugger, I can put breakpoints in my source code from webpack://./ sources and it will stop at those points. However, my code lies in file://./ so editing is not possible.

**Comment by thenikso** [comment]
any updates on this? It would be great if we could add an howto directly in the readme

**Comment by ricardolpd** [comment]
hi guys any updates on this, i have been pull my brains out trying to find a way to setup breakpoints in vscode, but i cant get the sourcemaps to work well, i am also using vs code.

**Comment by ricardolpd** [comment]
I finally got debugging working in vs code with this package:

The key to it was to set the devtool to:
`devtool: "source-map",`

and in 
```
output: {
    devtoolModuleFilenameTemplate: '[absolute-resource-path]',
    devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]'
}

```
as far as i can tell this is the only stopping it, however just as an example please find a working version of my config:

```
var path = require('path');
const webpack = require('webpack');
var nodeExternals = require('webpack-node-externals');

module.exports = {
  devtool: "source-map",
  debug: true,
  entry: {
    babelExample: 'example/babelExample.js',
    converse: 'converse/converse.js'
  },
  target: 'node',
  plugin: [
    new webpack.DefinePlugin({
      '__DEV__': true
    }),
    new webpack.HotModuleReplacementPlugin(),
  ],
  module: {
    preLoaders: [
      {
        test: /\.js$/,
        loaders: ['source-map'],
        include: __dirname,
      }
    ],
    externals: [nodeExternals()],
    loaders: [
      {
        test: /\.js$/,
        loaders: ['babel'],
        include: __dirname,
        exclude: /node_modules/
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      }
    ]
  },
  output: {
    devtoolModuleFilenameTemplate: '[absolute-resource-path]',
    devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]',
    libraryTarget: 'commonjs',
    path: path.join(__dirname, 'dist'),
    filename: '[name].js'
  },
  resolve: {
    root: [
      path.resolve(__dirname),
      path.resolve(__dirname, 'server'),
    ],
    extensions: ['', '.js', '.jsx']
  }
};
```
This allows me to debug interactively in vscode 1.9.1 with node debugger extension using node v4.3.2 runtime.

**Comment by jamesandersen** [comment]
@ricardolpd  I'm trying to follow your suggestions (using typescript in my case) and not having any luck so far.   Is your project public by chance?  I'm wondering if there's something I'm just missing...

**Comment by ricardolpd** [comment]
@jamesandersen no sorry the project is private and belongs to my workplace.
are you generating source maps?

the key bits for me to get it working with vs code was to use:
`devtool: "source-map",`
```
devtoolModuleFilenameTemplate: '[absolute-resource-path]',
devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]',
```

in my launch.json i also had to do:
```

"outFiles": [
                "${cwd}/<webpack_output_folder>/*"
            ],
 "sourceMaps": true,
 "smartStep": true
```

**Comment by deathweaselx86** [comment]
Do you know how to make source maps work with code that is not for API Gateway, preferably with node-inspector? `sls webpack invoke` runs too fast to send a debugging signal to and `sls webpack watch` ends up debugging the watch code.

**Comment by aheissenberger** [comment]
**To debug add:**
webpack.config.js: `devtool: 'source-map',`
add a `debugger` statement in your code
run `node --inspect --debug-brk ./node_modules/.bin/sls webpack serve`

for a complete example try my boilerplate and take a look into `package.json`:
https://github.com/aheissenberger/serverless-boilerplate
(webpack.config.js uses webpack 2.x Format - do not copy this if you use webpack 1.x - currently this is the default when installing `serverless-webpack`

**Comment by HyperBrain** [comment]
@aheissenberger 's approach seems to be working to debug. Closing this now. If you don't mind you can also try with a recent plugin version (and the new `3.0.0-rc.2` version).

**Comment by skylarmb** [comment]
For any future googlers, the solution for me was twofold. I had to make sure the configuration in Webstorm was running with `--inspect-brk` under "Node parameter". In addition to this there seems to be a quirk where breakpoints are only hit after a `debugger;` statement. I never had to use `debugger;`s in webstorm before using webpack, but now if I use a debugger statement, execution will stop there and any further breakpoints are respected.

**Comment by HyperBrain** [comment]
@skylarmb For me using VSCode adding `--lazy` additionally to the node command line to enable lazy breakpoint evaluation improved the situation too (at least when using babel-register). I'm not sure since which version of Node this is supported though.
