### ISSUE TITLE
Deploy function not executing webpack and deploys bogus ES6 functions

### ISSUE THREAD

**Issue by n8sabes** [elastic-coders/serverless-webpack#50]
`sls deploy function -f funcName` does not run webpack and deploys bogus (incomplete) functions that are missing imported code. `sls deploy` works correctly and deploys all functions build as defined in config.

Is this a bug, or is there a way to force single-function deployment to properly execute build instructions defined in `serverless.yml` and `webpack.config.js`?

Please see related issue [serverless issue #2454](https://github.com/serverless/serverless/issues/2453)

**Comment by msl-kabo** [comment]
I can confirm, I'm having this issue as well.

**Comment by thenikso** [comment]
this should get fixed by #48 and in v1 of this plugin (which will be released soon)
