### ISSUE TITLE
Can I put the plugins in a src directory?

### ISSUE THREAD

**Issue by andrewoh531** [elastic-coders/serverless-webpack#51]
I'm structuring my project so that at the root folder there is a `src` directory that contains all the code. I'd also like to put my `package.json` and the `node_modules` folder there including the `serverless-webpack` plugin.

Is it possible to have this structure? When I try this I get the error `Cannot find module 'serverless-webpack'` which I'm not sure how to resolve.

**Comment by thenikso** [comment]
well, npm searches for `node_modules` in the current directory which should be the one you have your `package.json` in and also the one from which you are running your `serverless` commands. 

So you can have your sources in `src` but for simplicity sake I'd leave you `node_modules` in the root directory of your project.

hope it helps
