### ISSUE TITLE
toUpperCase not found

### ISSUE THREAD

**Issue by PerryBirch** [elastic-coders/serverless-webpack#52]
There is a case when the http event comes back unparsed as a single string, this quick check (between for and const method) should alleviate:

serve.js - line: 43:

```
for (let httpEvent of funcConf.events) {

    if(typeof httpEvent === 'string'){
      var split = httpEvent.split(' ');
      httpEvent = {
        path: split[1],
        method: split[0],
      }
    }

    const method = httpEvent.method.toLowerCase();
    let endpoint = `/${httpEvent.path}`;
```

**Comment by thenikso** [comment]
I think you are referring to PR #45 which is still not merged. Please follow up on that PR to have updates on this issue
