### ISSUE TITLE
Implement a webpack watch command over all functions

### ISSUE THREAD

**Issue by miltador** [elastic-coders/serverless-webpack#56]
As I mentioned in #55, with the `serverless-offline` plugin the current `Simulate API Gateway locally` feature is pretty outdated and doesn't have so reach features as `serverless-offline` has. Nevertheless this plugin is great for bundling functions with webpack.
By working with this plugin and `serverless-offline` the only feature I miss is a watcher for changes in functions code with auto rebuilding.
This plugin has a `watch` command for separate function only. And a `serve` is overkill as it not only watches changes but hosts functions too.
It would be great to have a command for watching changes of the whole project code. In this case we probably want the plugin to run separately from `serverless-offline` so both can do their jobs.

**Comment by utkuturunc** [comment]
I don't mind having both plugins serve. How did you get serverless-offline work with serverless-webpack's output? All I can do is have them both serve at the same time. One's output is not piped to other's input.

**Comment by miltador** [comment]
@utkuturunc,
Watch #55, basically I added a hook into `serverless-webpack` so it makes a build before executing `serverless-offline`.  And I just run `serverless offline` and it builds my code and then serves it locally.

**Comment by utkuturunc** [comment]
@miltador I am using a similar solution. I want to implement watching feature to this solution.

**Comment by miltador** [comment]
@utkuturunc, I got it. I see it as 2 separate tasks running, one is webpack watcher and another one is `serverless offline`. `serverless-offline` plugin doesn't need a restart on code changes. Another approach I see is that webpack watcher will rebuild on code changes and then start `serverless-offline` plugin. I would prefer the second one as it is simpler for end users.

**Comment by utkuturunc** [comment]
I think the first choice is better. I am not sure how to handle node_modules though.

**Comment by thenikso** [comment]
I agree that we should have this plugin just do the build and leave the "offline" part to other plugins.

I still haven't grasped how to handle the hot-reloading though. I think it's a must have feature. I'll play around with #55. Any idea is welcome!
