### ISSUE TITLE
Implement custom authorizer support

### ISSUE THREAD

**Issue by ajagnanan** [elastic-coders/serverless-webpack#59]
Not sure if I configured something wrong, but I could not get the custom authorizer function to fire on secure endpoints. Could you add this please?

**Comment by thenikso** [comment]
with the recent rc3 release the compatibility for [serverless-offline (which supports custom authorizers)](https://github.com/dherault/serverless-offline#custom-authorizers) has been added. Could you try that and let us know?

**Comment by ajagnanan** [comment]
yea, i did use the serverless-offline plugin in addition to this one. It does work there.

**Comment by thenikso** [comment]
fantastic. I think it makes sense to specialise this plugin to do the webpack bundling alone. thanks for your feedback!
