### ISSUE TITLE
Make webpack a peer dependency so users can opt to use webpack 2

### ISSUE THREAD

**Issue by rvaidya** [elastic-coders/serverless-webpack#62]
As a peer dep, we can use whatever webpack version we want as long as it's above the minimum required version

https://github.com/rvaidya/serverless-webpack/tree/peerdep

**Comment by thenikso** [comment]
cool! could you open a PR to merge that change?

**Comment by utkuturunc** [comment]
Any updates on this?

**Comment by nikolasleblanc** [comment]
@rvaidya Jumping in here, any action on that PR?

**Comment by HyperBrain** [comment]
Released with version 2.0.0
