### ISSUE TITLE
serverless webpack serve without environment

### ISSUE THREAD

**Issue by bebbi** [elastic-coders/serverless-webpack#67]
It looks like `serverless webpack serve` doesn't add [environment vars](https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/functions.md#environment-variables) (serverless 1.2.0) defined in `serverless.yml` to the local environment.

**Comment by bebbi** [comment]
just confirmed that "native" `serverless invoke local -f func` does include these variables.

**Comment by thenikso** [comment]
this should have been addressed by #65 

Let us know if we should reopen this. thanks!
