### ISSUE TITLE
[1.0.0-rc3] 'core undefined' error on sls webpack serve

### ISSUE THREAD

**Issue by hassankhan** [elastic-coders/serverless-webpack#73]
Hi, love the project! Just upgraded to the newest version so I could check out the integration with `serverless-offline` and I get the following error:

```
Serverless: Serving functions...
  GET - http://localhost:8000/myapp
  GET - http://localhost:8000/myapp/resource1
  GET - http://localhost:8000/myapp/resource2
core undefined
core undefined
core undefined
```

All I did was update from 1.0.0-rc2 to rc3, and downgrading resolves the problem.

**Comment by singledigit** [comment]
This also happens when invoking locally.

**Comment by thenikso** [comment]
this should now be fixed in rc.4
