### ISSUE TITLE
[1.0.0-rc3] generated structure is different

### ISSUE THREAD

**Issue by simoami** [elastic-coders/serverless-webpack#76]
updated from 1.0.0-rc2 to rc3

RC2 output:
```
$ sls webpack
Serverless: Bundling with Webpack...
Time: 860ms
               Asset   Size  Chunks             Chunk Names
./functions/posts.js  26 kB       0  [emitted]  main
Serverless: Packing external modules: neo4j-driver@^1.1.0-M03, bluebird@^3.4.6, joi@^9.2.0, uuid@^3.0.1
```

RC3 output:
```
sls webpack
Serverless: Bundling with Webpack...
Time: 843ms
   Asset   Size  Chunks             Chunk Names
posts.js  26 kB       0  [emitted]  main
Serverless: Packing external modules: neo4j-driver@^1.1.0-M03, bluebird@^3.4.6, joi@^9.2.0, uuid@^3.0.1
```

The path difference causes the following error when invoking `sls webpack invoke -f name`:
```
  Error --------------------------------------------------

     Cannot find module '/projects/posts/.webpack/functions/posts.js'
```

downgrading resolves the problem.

**Comment by thenikso** [comment]
hmm I can't seam to be able to reproduce this. it seams a problem with the webpack configuration output path. It could be helpful if you include your webpack/serverless config or examples for them.

**Comment by simoami** [comment]
Here's my webpack.config:

```
const nodeExternals = require('webpack-node-externals');

module.exports = {
  entry: './functions/posts.js',
  target: 'node',
  externals: [nodeExternals()], // exclude external modules
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader'
      }
    ]
  }
};
```

And here's my project folder structure:
<img width="175" alt="screen shot 2017-01-09 at 11 44 45 am" src="https://cloud.githubusercontent.com/assets/2038264/21774729/667efd66-d661-11e6-9893-7cf83ff6fd07.png">

Notice the .webpack folder has a `functions` subfolder using rc2. try the same with rc3

**Comment by HyperBrain** [comment]
2.0.0 has been released recently and from now on the versioning will follow a strict SemVer pattern.
Is this issue still relevant?

**Comment by HyperBrain** [comment]
Closing this as it is very old and a lot of things changed. Feel free to add comments here - if there's need to create follow up issues, we'll do that.
