### ISSUE TITLE
Respond with output headers when using Lambda Proxy Integration

### ISSUE THREAD

**Issue by foysavas** [elastic-coders/serverless-webpack#84]
API Gateway now recognizes `statusCode`, `body`, and `headers` as part of [Lambda Function output](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html#api-gateway-simple-proxy-for-lambda-output-format).

Can we get `serverless-webpack` to pass along these headers as well?

In `server.js`:

        if (isLambdaProxyIntegration) {
          if (resp.headers) {
            for (let header in Object.keys(resp.headers)) {
              res.header(header, resp.headers[header]);
            }
          }
          res.status(resp.statusCode || 200).send(resp.body);
        } else {
          res.status(200).send(resp);
        }

**Comment by aheissenberger** [comment]
Here is a Link to a Code which does not work with the ´sls web pack serve´:
https://github.com/GorillaStack/serverless-redirect-example

alle headers are removes from the Response. Does work when deployed to AWS!

**Comment by abenab** [comment]
I've been wanting this fix too, however I think the following line of code should be:

`for (let header in resp.headers) {`
instead of:
`for (let header in Object.keys(resp.headers)) {`

**Comment by HyperBrain** [comment]
`serve` will be removed in the next `v3.0.0` release in favor of `serverless-offline` (see #152 ). No efforts will be spent on the function anymore. So I'll close this issue.
