### ISSUE TITLE
Serve: JSON Body Handling

### ISSUE THREAD

**Issue by jonsharratt** [elastic-coders/serverless-webpack#95]
Not sure if anyone else if having the same issue but the Lambda Proxy integration functions I have setup when deployed do not parse the JSON and thus the events `body` property requires parsing in my lambda function (e.g. https://github.com/craftship/yith/blob/master/src/user/put.js#L8) when a request is sent with `Content-Type` `application/json`.

In order to replicate the same functionallity when running the `webpack serve` command I had to do the following:
https://github.com/elastic-coders/serverless-webpack/compare/master...craftship:use-text-parser

I have not raised a PR yet as wanted to see if I was missing anything obvious / missed something I should test further.

Let me know, thanks for the awesome plugin has really helped our project long!

**Comment by anozaki** [comment]
I'm having the same problem.

This is a quote from the serverless documentation regarding lambda-proxy.
https://serverless.com/framework/docs/providers/aws/events/apigateway/
> Note: When the body is a JSON-Document, you must parse it yourself

**Comment by anozaki** [comment]
Just looked at your change. I think you need to do a little bit more. I think you only want to switch to text parser if the integration type is lambda-proxy.

**Comment by jonsharratt** [comment]
Will amend and raise the PR thanks for confirming this and taking a look into it :D

**Comment by HyperBrain** [comment]
@jonsharratt @anozaki If you use the serve functionality, it would be great if you could comment in #135 .

**Comment by HyperBrain** [comment]
`serve` will be removed in the next `v3.0.0` release in favor of `serverless-offline` (see #152 ). No efforts will be spent on the function anymore. So I'll close this issue.
