### ISSUE TITLE
update lambda function

### ISSUE THREAD

**Issue by barrytam20** [elastic-coders/serverless-webpack#98]
there is a serverless command to only update a lambda function, without touching cloud formation
serverless deploy function --function myFunction

is there this sort of functionality from serverless-webpack?

**Comment by andrewoh531** [comment]
This looks to be a duplicate of https://github.com/elastic-coders/serverless-webpack/issues/60

**Comment by HyperBrain** [comment]
Duplicate. Will keep #107, fixed with #130.
